// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sat Jun 16 19:37:06 2018

cpu68 cpu68_inst
(
	.clk(clk) ,	// input  clk
	.rst(rst) ,	// input  rst
	.rw(rw) ,	// output  rw
	.vma(vma) ,	// output  vma
	.address(address) ,	// output [15:0] address
	.data_in(data_in) ,	// input [7:0] data_in
	.data_out(data_out) ,	// output [7:0] data_out
	.hold(hold) ,	// input  hold
	.halt(halt) ,	// input  halt
	.irq(irq) ,	// input  irq
	.nmi(nmi) 	// input  nmi
);

